### ISSUE TITLE
gcc and not clang possible?

### ISSUE THREAD

**Issue by noobermin** [kwhat/crossdev-apple-overlay#1]
I'm curious if I understand this or not. Can this support gcc? Or does it work with clang only?

**Comment by kwhat** [comment]
You have to build sys-devel/binutils-apple with clang.  I tied to keep it gcc compatible for a while, but it became increasingly difficult.  If you use a version of sys-devel/apple-sdk before 10.9, you can probably compile with GCC without much trouble.  The biggest problem I have run into is that the more recent SDK's were back ported to add non-standard LLVM Blocks and other CLANG only garbage to the C API in the framework making it impossible to compile with GCC.
